[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "sllm"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn",
]

[tool.setuptools]
#package-dir = {"" = "src"}
package-dir = {"" = "."}


[tool.setuptools.packages.find]
where = ["."]
