[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "sllm"
version = "0.1.0"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn",
]
[tool.setuptools]
package-dir = {"sllm" = "."}
packages = [
    "sllm.core",
    "sllm.engine",
    "sllm.models",
    "sllm.processor",
    "sllm.runner",
    "sllm.server",
    "sllm.utils"
]

[[tool.uv.index]]
name = "tsinghua"
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true # 将其设为默认源